In [1]:
from dataclasses import dataclass

In [2]:
@dataclass
class volume:
    radius: int
    height: int
    pi:float = 3.14
        
    def cylinder(self):
        out= self.pi*(self.radius**2)*self.height
        return out
    
    def cone(self):
        out= 1/3*self.pi*(self.radius**2)*self.height
        return out

In [3]:
vol1=volume(3,6).cylinder()
vol1

169.56

In [4]:
vol2=volume(3,6).cone()
vol2

56.519999999999996

## Normal Class

In [1]:
class shape_volume:
    def __init__(self, radius, height):
        self.radius= radius
        self.height= height
        self.pi= 3.14

    def cylinder(self):
        return (self.pi*self.radius**2*self.height)

    def cone(self):
        return (1/3*self.pi*self.radius**2*self.height)

In [2]:
obj=shape_volume(3,4)

print(obj.cylinder())

113.04

In [3]:
obj.__dict__

{'radius': 3, 'height': 4, 'pi': 3.14}

## Encapsulation

- In encapsulation input arguments of class is private, we can't modify the values of input arguments with help of object.
- Normally in OOPs we can modify the values of input arguments of class through object by calling class name.variable modify value
- In encapsulation even though input arguments are private, we can see the arguments value by 'obj._class__args'

In [31]:
class bank_acct:
    def __init__(self, name, acct_no, balance):
        self.__balance:float = balance
        self.__name:str = name
        self.__acct_no:int = acct_no

    def show_balance(self):
        return (f"your current balance:{self.__balance}")

    def deposit(self, amount):
        self.__balance = self.__balance + amount
        return (f'Amount deposited successfully, your balance: {self.__balance}')

    def withdraw(self, amount):
        if amount <= self.__balance: 
            self.__balance = self.__balance - amount
            return (f'Amount withdrawed, your current balance: {self.__balance}')

    def personal_details(self):
        print (f'Name:{self.__name} \nAcct_No:{self.__acct_no} \nBalance:{self.__balance}')

In [37]:
sbi=bank_acct('mani',1913,10000)

In [38]:
sbi.__dict__

{'_bank_acct__balance': 10000,
 '_bank_acct__name': 'mani',
 '_bank_acct__acct_no': 1913}

In [39]:
# In encapsulation even though input arguments are private, we can see the arguments value by 'obj._class__args'
sbi._bank_acct__name

'mani'

In [21]:
sbi.show_balance()

'your current balance:10000'

In [22]:
sbi.deposit(2500)

'Amount deposited successfully, your balance: 12500'

In [23]:
sbi.withdraw(5000)

'Amount withdrawed, your current balance: 7500'

In [32]:
sbi.personal_details()

'Name:mani \nAcct_No:1913 \nBalance:7500'

## Inheritance

In [49]:
class car1:
    def __init__(self, make, manuf, year):
        self.make= make
        self.manuf= manuf
        self.year= year

    def car_details(self):
        return (f"car company is:{self.make}, car name is:{self.manuf}, it's made in {self.year}")


class car2(car1):
    def __init__(self, varient, drive):
        self.varient= varient
        self.drive= drive

    def car_varients(self):
        return (f"car is a {self.varient}, {self.drive} model")

class car3(car2):
    def review(self):
        return ('it a very good car with highest safety rating of NCAP:5')

In [52]:
tata_car1= car1('tata','safari','2023')
tata_car2= car2('petrol', '4w')

In [53]:
tata_car2.car_varients()

'car is a petrol, 4w model'

In [54]:
tata_car1.car_details()

"car company is:tata, car name is:safari, it's made in 2023"

In [64]:
tata_car3= car3('diesel','2w')

In [65]:
tata_car3.__dict__

{'varient': 'diesel', 'drive': '2w'}

In [66]:
tata_car3.review()

'it a very good car with highest safety rating of NCAP:5'

In [67]:
# Able to access the methods or properties of car2 class through tata_car2 object

tata_car3.car_varients()

'car is a diesel, 2w model'

## Decorator

In [81]:
import time

def decorator(func):
    def decorator_wrapper(num):
        start= time.time()
        print(f"Checking if {num} is a prime number...")
        result=func(num)
        print(result)
        print(f'Given function stopped')
        end= time.time()
        print(f'Time taken:{start-end}')
    return decorator_wrapper

In [83]:
@decorator
def check_prime_num(num):
    if num > 1:
        for i in range(2, num):
            if num % i == 0:
                return f'Given {num} is not a prime number'
        else:
            return f'Given {num} is a prime number'
    else:
        return f'Given {num} is not a prime number'

check_prime_num(22)

Checking if 22 is a prime number...
Given 22 is not a prime number
Given function stopped
Time taken:-0.0003914833068847656

### Class- Static Method

In [35]:
class maths:
    def __init__(self):
        self.pi= 3.14

    def vol_cylinder(self, radius, height):
        return (self.pi*radius**2*height)

    @staticmethod
    def vol_cone(radius, height):
        return (1/3*3.14*radius**2*height)

In [31]:
cylind= maths()

In [32]:
cylind.__dict__

{'pi': 3.14}

In [33]:
cylind.vol_cylinder(3,4)

113.04

In [36]:
'''if we use staticmethod decorator for properties or methods in class, 
we can directly access the method and pass values into it. instead of assigning it to object and then call it use the methods
we don't need to mention self in function arguments, just pass arguments when using static decorator. it reduces the memory consumption 
'''

maths().vol_cone(2,3)

12.559999999999999

## Interview code 
### inp='africa', out: ['af', 'ri', 'ca']

In [5]:
inp='africa'

out=[inp[i:i+2] for i in range(0, len(inp),2)]
out

['af', 'ri', 'ca']

## Interview qstn Input='My Name is Lisa' expected Output= 'as iLsi em aNyM'

In [28]:
def reverse_string_keep_spaces(s):
    space_index= [i for i, ch in enumerate(s) if ch==' ']
    
    str= [ch for ch in s if ch!=' ']
    rev_str= str[::-1]
    
    result=[]
    
    index=0
    for idx in range(len(s)):
        if idx in space_index:
            result.append(' ')
        else:
            result.append(rev_str[index])
            index+=1
    
    return ''.join(result)

s= 'My Name is Lisa'
reverse_string_keep_spaces(s)

'as iLsi em aNyM'

## Interview QSTN

Input: nums= [10,9, 2,5,3,7,101,18]

write a python function that returns the length of the longest strictly increasing sequence of nums answers is 4

Output: 4 (2,3,7,18)

In [5]:
from bisect import bisect_left

def length_of_lis(nums):
    sub=[]
    for num in nums:
        i=bisect_left(sub, num)
        if i == len(sub):
            sub.append(num)
        else:
            sub[i]=num
    return len(sub), sub

In [6]:
nums= [10,9, 2,5,3,7,101,18]
length_of_lis(nums)

(4, [2, 3, 7, 18])

### Interview qstn text= 'abcabccb' and output 'abcaabbcccccbbb'

In [7]:
text ='abcabccb'

result= []
count={}
for ch in text:
    count[ch]=count.get(ch,0) +1
    result.append(ch*count[ch])
res= ''.join(result)
res

'abcaabbcccccbbb'

In [23]:
## Interview qstn Input='My Name is Lisa' expected Output= 'as iLsi em aNyM'

text= 'My Name is Lisa'

result=[]
space= [i for i, ch in enumerate(text) if ch==' ']

words= [ ch for ch in text if ch!=' ']
rev_text= words[::-1]

num=0
for idx in range(len(text)):
    if idx in space:
        result.append(' ')
    else:
        result.append(rev_text[num])
        num+=1

final= ' '.join(result)
final

'a s   i L s i   e m   a N y M'

### Interview qstn asked in AMERICAN EXPRESS 

text= 'catsanddog'

Iterator= ['cat', 'and', 'dog']

print true if text matches with iterator else false

In [9]:
text= 'catsanddog'
Iterator= ['cat', 'and', 'dog']

result=[]
for i in range(len(text)+1):
    temp=[]
    for j in range(1, len(text)+1):
        #print(text[i:j])
        if text[i:j] in Iterator:
            temp.append((text[i:j], True))
        else:
            temp.append((text[i:j], False))
    result.append(temp)
    
result

[[('c', False),
  ('ca', False),
  ('cat', True),
  ('cats', False),
  ('catsa', False),
  ('catsan', False),
  ('catsand', False),
  ('catsandd', False),
  ('catsanddo', False),
  ('catsanddog', False)],
 [('', False),
  ('a', False),
  ('at', False),
  ('ats', False),
  ('atsa', False),
  ('atsan', False),
  ('atsand', False),
  ('atsandd', False),
  ('atsanddo', False),
  ('atsanddog', False)],
 [('', False),
  ('', False),
  ('t', False),
  ('ts', False),
  ('tsa', False),
  ('tsan', False),
  ('tsand', False),
  ('tsandd', False),
  ('tsanddo', False),
  ('tsanddog', False)],
 [('', False),
  ('', False),
  ('', False),
  ('s', False),
  ('sa', False),
  ('san', False),
  ('sand', False),
  ('sandd', False),
  ('sanddo', False),
  ('sanddog', False)],
 [('', False),
  ('', False),
  ('', False),
  ('', False),
  ('a', False),
  ('an', False),
  ('and', True),
  ('andd', False),
  ('anddo', False),
  ('anddog', False)],
 [('', False),
  ('', False),
  ('', False),
  ('', False),
  ('', False),
  ('n', False),
  ('nd', False),
  ('ndd', False),
  ('nddo', False),
  ('nddog', False)],
 [('', False),
  ('', False),
  ('', False),
  ('', False),
  ('', False),
  ('', False),
  ('d', False),
  ('dd', False),
  ('ddo', False),
  ('ddog', False)],
 [('', False),
  ('', False),
  ('', False),
  ('', False),
  ('', False),
  ('', False),
  ('', False),
  ('d', False),
  ('do', False),
  ('dog', True)],
 [('', False),
  ('', False),
  ('', False),
  ('', False),
  ('', False),
  ('', False),
  ('', False),
  ('', False),
  ('o', False),
  ('og', False)],
 [('', False),
  ('', False),
  ('', False),
  ('', False),
  ('', False),
  ('', False),
  ('', False),
  ('', False),
  ('', False),
  ('g', False)],
 [('', False),
  ('', False),
  ('', False),
  ('', False),
  ('', False),
  ('', False),
  ('', False),
  ('', False),
  ('', False),
  ('', False)]]

## Interview Question without using Sort built-in function need to print numbers in ascending order

In [3]:
lis=[4,7,8,3,2,6,1]

In [7]:
for i in range(0,len(lis)):
    for j in range(i+1,len(lis)):
        if lis[i]>lis[j]:
            lis[i],lis[j]=lis[j],lis[i]

In [7]:
lis

[1, 2, 3, 4, 6, 7, 8]

## Interview question- Vowels count in a sentence

In [1]:
def vowel_count(text):
    vowel=['a','i','o','e','u']
    count = {}.fromkeys(vowel, 0)
    
    for char in text:
        if char in count:
            count[char]+=1
    return count

if __name__=="__main__":
    text=input("Enter text : ")
    print(vowel_count(text))

Enter text :  I'm a Data Scientist

{'a': 3, 'i': 2, 'o': 0, 'e': 1, 'u': 0}

## Interview question- without using sort built-in function need to get max numbers in give list

In [1]:
num=[4,6,7,2,3,1,5,9]

In [10]:
for i in range(len(num)):
    for j in range(i+1, len(num)):
        if num[i]>num[j]:
            num[i],num[j]=num[j],num[i]

num[-1]

9

## Map function

In [1]:
def square(num):
    return num*num

In [2]:
numbers=[2,4,5,6,7,8,9,11]

In [5]:
square_num=list(map(square, numbers))

In [6]:
square_num

[4, 16, 25, 36, 49, 64, 81, 121]

In [7]:
temp=[]
for i in numbers:
    temp.append(square(i))

print(temp)

[4, 16, 25, 36, 49, 64, 81, 121]

## Filter function

In [8]:
def even_check(num):
    if num%2==0:
        return True
    else:
        return False

In [13]:
numbers=[2,4,5,6,7,8,9,11,12,21,23]

In [10]:
output= list(filter(even_check, numbers))

print(output)

[2, 4, 6, 8, 12]

In [14]:
out= list(filter(lambda x: True if x>18 else False, numbers))
print(out)

[21, 23]

## Reduce function

In [15]:
from functools import reduce

In [26]:
nums=[2,4,8,15,7,35,6]

In [27]:
max(nums)

35

In [28]:
result=reduce(lambda a,b: a if a>b else b, nums)

print(result)

35

In [29]:
def max_num(a,b):
    if a>b:
        return a
    else:
        return b

In [23]:
result1= reduce(max_num, nums)
result1

25

### Print first ten PrimeNo

In [3]:
def is_prime(num):
    if num>1:
        for i in range(2, num):
            if num%i==0:
                return False
                break
        else:
            return True
    else:
        return False    

prime=[]
num=1
while len(prime) < 10:
    if is_prime(num):
        prime.append(num)
    num+=1

prime

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29]

### Find the PrimeNo's in a given set of list or array

In [4]:
def is_prime(n):
    if n>1:
        for i in range(2, n):
            if n%i==0:
                return False
        else:
            return True
    else: 
        return False
        
num=[5,7,8,9,21,22,11,13,4]

out=list(filter(is_prime, num))
out

[5, 7, 11, 13]

### Fibonacci function

In [3]:
def fibonacci_func(n):
    a,b=0,1
    for x in range(n):
        yield a
        a,b = b, a+b

In [5]:
# one approach to see output

for x in fibonacci_func(12):
    print(x)

0
1
1
2
3
5
8
13
21
34
55
89

In [4]:
# second approach to see output
out= list(fibonacci_func(10))
out

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]

## Interview question
### Input=[15,25,20,5,35, 23], Out: ['1', '2', '20', '3', '23']

In [33]:
num=[15,25,20,5,35, 23]

out=[]
for nm in num:
    temp=[]
    for n in str(nm):
        if '5' not in n:
            temp.append(n)
    res=''.join(temp)
    if res!='':
         out.append(res)

In [34]:
out

['1', '2', '20', '3', '23']

In [53]:
num=[4,7,8,3,2,6,1]

In [56]:
num.sort(reverse=True)

In [58]:
num=[15,25,20,5,35, 23]

In [66]:
out

['1', '2', '20', '3', '23']

In [1]:
import pandas as pd

df= pd.DataFrame({'AGREEMENTNO':[123,124,122,127,128],'Fisrt_EMI':[12,13,14,15,16], 'last_emi':[21,22,23,24,25]})
df.head()

   AGREEMENTNO  Fisrt_EMI  last_emi
0          123         12        21
1          124         13        22
2          122         14        23
3          127         15        24
4          128         16        25

In [2]:
import pandas as pd

df1= pd.DataFrame({'AGREEMENTNO':[123,124,132,129,130],'Fisrt_EMI':[17,18,19,20,21], 'last_emi':[26,27,28,29,30]})
df1.head()

   AGREEMENTNO  Fisrt_EMI  last_emi
0          123         17        26
1          124         18        27
2          132         19        28
3          129         20        29
4          130         21        30

In [3]:
final= df.merge(df1, on='AGREEMENTNO', how='inner')
final.head()

   AGREEMENTNO  Fisrt_EMI_x  last_emi_x  Fisrt_EMI_y  last_emi_y
0          123           12          21           17          26
1          124           13          22           18          27

In [5]:
dfs= df.loc[~(df['AGREEMENTNO'].isin(final['AGREEMENTNO']))]
dfs.head()

   AGREEMENTNO  Fisrt_EMI  last_emi
2          122         14        23
3          127         15        24
4          128         16        25

In [6]:
dfrs= df.loc[~(df['AGREEMENTNO'].isin(df1['AGREEMENTNO']))]
dfrs.head()

   AGREEMENTNO  Fisrt_EMI  last_emi
2          122         14        23
3          127         15        24
4          128         16        25

In [7]:
dfrs1=  df1.loc[~(df1['AGREEMENTNO'].isin(df['AGREEMENTNO']))]
dfrs1.head()

   AGREEMENTNO  Fisrt_EMI  last_emi
2          132         19        28
3          129         20        29
4          130         21        30

In [8]:
final= pd.concat([dfrs,dfrs1])
final.head()

   AGREEMENTNO  Fisrt_EMI  last_emi
2          122         14        23
3          127         15        24
4          128         16        25
2          132         19        28
3          129         20        29